name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.13.0
  firebase_core: ^2.24.0
  firebase_ui_auth: ^1.10.0
  firebase_ui_firestore: ^1.5.14
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_svg: ^2.0.9
  go_router: ^12.1.3
  intl: ^0.18.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  random_string: ^2.3.1
  flutter_lints: ^3.0.1
  # a tool for running code generators
  build_runner: ^2.4.7
  # the code generator
  riverpod_generator: ^2.3.9
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.7
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
